# Generated by Django 5.2.4 on 2025-07-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipemodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starclinchbaseuser',
            name='user_type',
            field=models.CharField(choices=[('ADM', 'Admin'), ('Dev', 'Developer'), ('Customer', 'Customer'), ('Seller', 'Seller')], db_index=True, default='User', max_length=20, verbose_name='User Type'),
        ),
    ]
